### ISSUE TITLE
helpers.ts fails with yarn test

### ISSUE THREAD

**Issue by stefan-nikolov96** [metacraft-labs/DendrETH#213]
```
FAIL  tests/helpers/helpers.ts
 ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:172:18)
      at node_modules/@jest/core/build/TestScheduler.js:300:17
          at Array.map (<anonymous>)

```

Do we have any unadded tests @kkirkov ? Please fix, since this is the only failing test.

**Comment by stefan-nikolov96** [comment]
Fixed

**Comment by stefan-nikolov96** [comment]
Fixed
